[package]
name = "hybrid-format-impls"
description = "Use the hybrid-format crate."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
const-zmij = "0.1.0"
lexical-core = {version="1.0.6", default-features=false, features=["write-integers"]}
zmij = "1.0.23"

[lints]
workspace = true