[package]
name = "hybrid-format"
version = "0.1.0"
edition = "2024"

[dependencies]
hybrid-format-macros = {path = "../hybrid-format-macros"}
hybrid-format-impls = {path = "../hybrid-format-impls"}
const_format = "0.2.36"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "format"
harness = false