[package]
name = "hybrid-format"
description = "A hybrid format! alternative that formats constants at compile-time and everything else much faster at runtime with a single allocation. Extensible with your own types and no_std."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hybrid-format-macros.workspace = true
const_format = "0.2.36"
const-zmij = "0.1.0"
lexical-core = {version="1.0.6", default-features=false, features=["write-integers"]}
zmij = "1.0.23"

[dev-dependencies]
criterion = "0.8.2"

[lints]
workspace = true

[[bench]]
name = "format"
harness = false