[package]
name = "hybrid-format"
description = "A `format!` alternative that formats constants at compile-time and everything else much faster at runtime with a single allocation. Extensible with your own types and no_std."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hybrid-format-macros.workspace = true
hybrid-format-impls.workspace = true
const_format = "0.2.36"

[dev-dependencies]
criterion = "0.8.2"

[lints]
workspace = true

[[bench]]
name = "format"
harness = false